### ISSUE TITLE
AttributeError: 'Motion_MDP' object has no attribute 'edge'

### ISSUE THREAD

**Issue by hapoy9** [MengGuo/P_MDP_TG#1]
您好！请您原谅我用中文向您请教一些问题，担心自己英文无法描述清楚自己的问题。对您这个项目比较感兴趣，但是查阅您谷歌学术的论文也没有找到该项目对应的论文，您能提供一下该项目的相关论文吗？此外，我在运行此项目的test_example.py时，产生一下错误：
`Traceback (most recent call last):
  File "test_example.py", line 61, in <module>
    motion_mdp = Motion_MDP(node_dict, edge_dict, U, initial_node, initial_label)
  File "C:\Users\keyan\Desktop\P_MDP_TG-master\P_MDP_TG-master\MDP_TG\mdp.py", line 16, in __init__
    self.add_edges(edge_dict, U)
  File "C:\Users\keyan\Desktop\P_MDP_TG-master\P_MDP_TG-master\MDP_TG\mdp.py", line 41, in add_edges
    prop = self.edge[f_node][t_node]['prop']
AttributeError: 'Motion_MDP' object has no attribute 'edge'`
您在mdp.py没有定义edge属性，而且在基类digraph.py中也没有该属性，只有edges方法，所以prop = self.edge[f_node][t_node]['prop']报错，我尝试修改为edges也没有解决问题，不太理解您这句的含义，麻烦您帮忙解决一下，非常感谢！

**Comment by MengGuo** [comment]
Thanks for the interest!

For now, you may refter/cite the axiv version: https://arxiv.org/pdf/1706.05209.pdf

The `edge` error is due to the incompatibility between networkx 1.x and networkx 2.0. `edge[][]` is not allowed in 2.0 anymore. The modification should be very simple. You could:

  . use networkx 1.x
  . use networkx 2.0 and fix these incompatibilities. And send me a merge request. 
  . I will let you know when I move this repo to networkx 2.0 (most likely in the next month).

Let me know, so we don't double the work. 
/Meng

**Comment by hapoy9** [comment]
@MengGuo 非常感谢您的帮助，我利用networkx 1.9代替，`edge`错误解决了，由于我是在Windows下面运行的程序，修改了ltl2dra.py中的`cmd = "echo \"%s\"" % formula + " | " + "./MDP_TG/ltl2dstar.exe " + "--ltl2nba=spin:./MDP_TG/ltl2ba.exe --stutter=no - -"`，报错为：
`Traceback (most recent call last):
  File "test_example.py", line 70, in <module>
    dra = Dra(sur_formula1)
  File "C:\Users\keyan\Desktop\P_MDP_TG-master\P_MDP_TG-master\MDP_TG\dra.py", line 18, in __init__
    ltl2dra_output = run_ltl2dra(formula)
  File "C:\Users\keyan\Desktop\P_MDP_TG-master\P_MDP_TG-master\MDP_TG\ltl2dra.py", line 21, in run_ltl2dra
    raw_output = check_output(cmd, shell=True)
  File "C:\Python27\lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'echo "& G F a & G F b G F c" | ./MDP_TG/ltl2dstar.exe --ltl2nba=spin:./MDP_TG/ltl2ba.exe --stutter=no - -' returned non-zero exit status 255`
由于Linux命令不是特别熟悉，不知道是不是cmd命令代码出现了问题，我也在摸索，您有什么建议吗？

**Comment by hapoy9** [comment]
@MengGuo 非常感谢您的帮助，根据您的建议使用networkx 1.9，现在`edge`的报错已经没有了，但是我将ltl2ba等换成了Windows版本后，调试又遇到一个新的问题，在promela.py中的代码抛出了异常，异常位置为：
`if self.accept(Parser.title_regex) == None:
            raise Exception("Expected 'DRA title' but got %s" % self.instring[self.pos])`
程序输出和错误提示为：
`-------Motion MDP Initialized-------
-------Motion MDP Constructed-------
4 states and 12 edges
Unify MDP Done
Traceback (most recent call last):
  File "test_example.py", line 70, in <module>
    dra = Dra(sur_formula1)
  File "C:\Users\keyan\Desktop\P_MDP_TG-master\P_MDP_TG-master\MDP_TG\dra.py", line 20, in __init__
    statenum, init, edges, aps, acc = parse_dra(ltl2dra_output)
  File "C:\Users\keyan\Desktop\P_MDP_TG-master\P_MDP_TG-master\MDP_TG\ltl2dra.py", line 29, in parse_dra
    states, init, edges, aps, acc = parser.parse()
  File "C:\Users\keyan\Desktop\P_MDP_TG-master\P_MDP_TG-master\MDP_TG\promela.py", line 50, in parse
    raise Exception("Expected 'DRA title' but got %s" % self.instring[self.pos])
Exception: Expected 'DRA title' but got D`
我将项目中complex_case_study的例子运行出现了同样的错误，不知问题出在了哪里？

**Comment by MengGuo** [comment]
Hello, there is another executable `ltl2dstar` https://github.com/MengGuo/P_MDP_TG/blob/master/MDP_TG/ltl2dstar   You may need the windows version for that also. 

nevertheless, switch to Linux/unix if possible as it would make your life much easier. 
/Meng

**Comment by hapoy9** [comment]
@MengGuo 我已经将`ltl2dstar`替换为[http://www.ltl2dstar.de/](http://www.ltl2dstar.de/)提供的Windows版本，运行才出现的那个问题，如果没有替换windows版本直接报subprocess.CalledProcessError错误，而不是抛出异常，难道是我版本问题吗？我用终端执行ltl2dstra语句是有结果返回的，附图是执行的结果，麻烦您看一下有问题吗？如果一直没有解决我会接受您的建议在ubuntu下面运行该程序。
![result](https://user-images.githubusercontent.com/16236178/33645034-b1a6f664-da83-11e7-8209-abdc61d5acce.png)

**Comment by hapoy9** [comment]
@MengGuo 再次打扰您十分抱歉，在您的帮助下，今天我在ubuntu下面已经有了规划结果，但是没有可视化界面，这是什么原因呢？需要怎么做可以通过可视化界面，直观的看出规划结果，如同您仿真视频里面那样？十分期待您的回复，非常感谢！[https://people.kth.se/~mengg/P_MDP_TG.html](https://people.kth.se/~mengg/P_MDP_TG.html)

**Comment by mingyucai** [comment]
> @MengGuo 我已经将`ltl2dstar`替换为http://www.ltl2dstar.de/提供的Windows版本，运行才出现的那个问题，如果没有替换windows版本直接报subprocess.CalledProcessError错误，而不是抛出异常，难道是我版本问题吗？我用终端执行ltl2dstra语句是有结果返回的，附图是执行的结果，麻烦您看一下有问题吗？如果一直没有解决我会接受您的建议在ubuntu下面运行该程序。
> ![result](https://user-images.githubusercontent.com/16236178/33645034-b1a6f664-da83-11e7-8209-abdc61d5acce.png)
That's correct. But it's better to use ubuntu to save time.

**Comment by LiuZesensengsheng** [comment]
> @MengGuo 我已经将`ltl2dstar`替换为http://www.ltl2dstar.de/提供的Windows版本，运行才出现的那个问题，如果没有替换windows版本直接报subprocess.CalledProcessError错误，而不是抛出异常，难道是我版本问题吗？我用终端执行ltl2dstra语句是有结果返回的，附图是执行的结果，麻烦您看一下有问题吗？如果一直没有解决我会接受您的建议在ubuntu下面运行该程序。
> ![result](https://user-images.githubusercontent.com/16236178/33645034-b1a6f664-da83-11e7-8209-abdc61d5acce.png)

Mr. Guo , I met the same question in Ubuntu and it seems that my ltl2dstar is correct.

**Comment by MengGuo** [comment]
@hapoy9 @mingyucai @LiuZesensengsheng I can't verify this, but have you guys also compiled `ltl2dstar` for your OS? as mentioned [here](https://github.com/MengGuo/P_MDP_TG/blob/master/README.md#dependence)?

**Comment by SJTUGuofei** [comment]
> > @MengGuo 我已经将`ltl2dstar`替换为[http://www.ltl2dstar.de/提供的Windows版本，运行才出现的那个问题，如果没有替换windows版本直接报subprocess.CalledProcessError错误，而不是抛出异常，难道是我版本问题吗？我用终端执行ltl2dstra语句是有结果返回的，附图是执行的结果，麻烦您看一下有问题吗？如果一直没有解决我会接受您的建议在ubuntu下面运行该程序。](http://www.ltl2dstar.de/%E6%8F%90%E4%BE%9B%E7%9A%84Windows%E7%89%88%E6%9C%AC%EF%BC%8C%E8%BF%90%E8%A1%8C%E6%89%8D%E5%87%BA%E7%8E%B0%E7%9A%84%E9%82%A3%E4%B8%AA%E9%97%AE%E9%A2%98%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%B2%A1%E6%9C%89%E6%9B%BF%E6%8D%A2windows%E7%89%88%E6%9C%AC%E7%9B%B4%E6%8E%A5%E6%8A%A5subprocess.CalledProcessError%E9%94%99%E8%AF%AF%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF%E6%8A%9B%E5%87%BA%E5%BC%82%E5%B8%B8%EF%BC%8C%E9%9A%BE%E9%81%93%E6%98%AF%E6%88%91%E7%89%88%E6%9C%AC%E9%97%AE%E9%A2%98%E5%90%97%EF%BC%9F%E6%88%91%E7%94%A8%E7%BB%88%E7%AB%AF%E6%89%A7%E8%A1%8Cltl2dstra%E8%AF%AD%E5%8F%A5%E6%98%AF%E6%9C%89%E7%BB%93%E6%9E%9C%E8%BF%94%E5%9B%9E%E7%9A%84%EF%BC%8C%E9%99%84%E5%9B%BE%E6%98%AF%E6%89%A7%E8%A1%8C%E7%9A%84%E7%BB%93%E6%9E%9C%EF%BC%8C%E9%BA%BB%E7%83%A6%E6%82%A8%E7%9C%8B%E4%B8%80%E4%B8%8B%E6%9C%89%E9%97%AE%E9%A2%98%E5%90%97%EF%BC%9F%E5%A6%82%E6%9E%9C%E4%B8%80%E7%9B%B4%E6%B2%A1%E6%9C%89%E8%A7%A3%E5%86%B3%E6%88%91%E4%BC%9A%E6%8E%A5%E5%8F%97%E6%82%A8%E7%9A%84%E5%BB%BA%E8%AE%AE%E5%9C%A8ubuntu%E4%B8%8B%E9%9D%A2%E8%BF%90%E8%A1%8C%E8%AF%A5%E7%A8%8B%E5%BA%8F%E3%80%82)
> > ![result](https://user-images.githubusercontent.com/16236178/33645034-b1a6f664-da83-11e7-8209-abdc61d5acce.png)
> > That's correct. But it's better to use ubuntu to save time.

**Which version Ubuntu is preferred? I use Ubuntu22, and there are some issues when run the examples?**


-------Motion MDP Initialized-------
-------Motion MDP Constructed-------
1444 states and 13696 edges
Unify MDP Done
MDP done, time: 0.30488014221191406
/home/figo/P_MDP_TG/MDP_TG/ltl2dstar
/bin/sh: 1: /home/figo/P_MDP_TG/MDP_TG/ltl2dstar: Exec format error
Traceback (most recent call last):
  File "/home/figo/P_MDP_TG/case_study_rex_changesize.py", line 154, in <module>
    dra = Dra(all_base)
  File "/home/figo/P_MDP_TG/MDP_TG/dra.py", line 20, in __init__
    ltl2dra_output = run_ltl2dra(formula)
  File "/home/figo/P_MDP_TG/MDP_TG/ltl2dra.py", line 27, in run_ltl2dra
    raw_output = check_output(cmd, shell=True)
  File "/home/figo/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/figo/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'echo "& G F base1 & G F base2 & G F base3 G ! obstacle" | /home/figo/P_MDP_TG/MDP_TG/ltl2dstar --ltl2nba=spin:/home/figo/P_MDP_TG/MDP_TG/ltl2ba --stutter=no - -' returned non-zero exit status 126.

**Comment by MengGuo** [comment]
@SJTUGuofei it seems to be related your `ltl2ba` version. Make sure to compile under your OS from source.
